plugins {
    id 'com.android.application'
}

android {
    namespace 'com.recapify.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.recapify.app'
        minSdk 21
        targetSdk 28
        versionCode 2
        versionName '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
